name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Sync deps
        run: uv sync

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Tests (pytest)
        run: uv run pytest -q

      # Optional: smoke the CLI; allow failure in case the site blocks CI IPs
      - name: Smoke CLI
        run: uv run python -m tradingdatafetcher.cli --interval monthly --out /tmp/out.csv || true
